-- 코드를 입력하세요
SELECT a.BOOK_ID, b.AUTHOR_NAME, to_char(a.PUBLISHED_DATE, 'yyyy-mm-dd') as PUBLISHED_DATE
FROM BOOK a INNER JOIN AUTHOR b
ON a.AUTHOR_ID = b.AUTHOR_ID
WHERE a.CATEGORY = '경제'
ORDER BY a.PUBLISHED_DATE ASC